/**
 * Array of available Devices.
 *
 * @type {*[]}
 */
const DEVICES = {
  'galaxyS3': {
    'portrait': {
      color: ['black', 'white',],
      image_width: 833,
      image_height: 1622,
      screen_top: 157,
      screen_right: 59,
      screen_bottom: 185,
      screen_left: 55,
      button_top: 1511,
      button_right: 323,
      button_bottom: 58,
      bottom_left: 322,
      screen_width: 720,
      screen_height: 1280,
    },
    'landscape':{
      orientation: 'landscape',
      color: ['black', 'white',],
      image_width:  1622,
      image_height: 834,
      screen_top: 59,
      screen_right: 190,
      screen_bottom: 55,
      screen_left: 152,
      button_top: 324,
      button_right: 53,
      button_bottom: 322,
      bottom_left: 1514,
      screen_width: 1280,
      screen_height: 720,
    },
  },
  'galaxyS5': {
    'portrait': {
      color: ['black', 'white', 'gold',],
      image_width: 1230,
      image_height: 2386,
      screen_top: 234,
      screen_right: 75,
      screen_bottom: 232,
      screen_left: 75,
      button_top: 2210,
      button_right: 474,
      button_bottom: 87,
      bottom_left: 479,
      screen_width: 1080,
      screen_height: 1920,
    },
    'landscape': {
      color: ['black', 'white', 'gold',],
      image_width: 2386,
      image_height: 1230,
      screen_top: 75,
      screen_right: 232,
      screen_bottom: 75,
      screen_left: 234,
      button_top: 474,
      button_right: 87,
      button_bottom: 479,
      bottom_left: 2210,
      screen_width: 1920,
      screen_height: 1080,
    },
  },
  'galaxyTab4': {
    'portrait': {
      color: ['black', 'white',],
      image_width: 1178,
      image_height: 1983,
      screen_top: 170,
      screen_right: 75,
      screen_bottom: 167,
      screen_left: 67,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'iMac': {
    'portrait': {
      color: ['black',],
      image_width:  1843,
      image_height: 1483,
      screen_top: 75,
      screen_right: 75,
      screen_bottom: 456,
      screen_left: 75,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
      screen_width: 768,
      screen_height: 1024,
    },
  },
  'iPad': {
    'portrait': {
      color: ['black', 'white',],
      image_width: 1116,
      image_height: 1446,
      screen_top: 132,
      screen_right: 114,
      screen_bottom: 137,
      screen_left: 117,
      button_top: 1347,
      button_right: 523,
      button_bottom: 34,
      bottom_left: 526,
      screen_width: 1024,
      screen_height: 768,
    },
    'landscape': {
      color: ['black', 'white',],
      image_width: 1446,
      image_height: 1114,
      screen_top: 114,
      screen_right: 136,
      screen_bottom: 115,
      screen_left: 134,
      button_top: 521,
      button_right: 34,
      button_bottom: 526,
      bottom_left: 1348,
    },
  },
  'iPadAir2': {
    'portrait': {
      color: ['black', 'white', 'gold',],
      image_width: 1766,
      image_height: 2497,
      screen_top: 227,
      screen_right: 116,
      screen_bottom: 222,
      screen_left: 114,
      button_top: 2336,
      button_right: 828,
      button_bottom: 50,
      bottom_left: 827,
      screen_width: 1536,
      screen_height: 2048,
    },
    'landscape': {
      color: ['black', 'white', 'gold',],
      image_width: 2497,
      image_height: 1766,
      screen_top: 116,
      screen_right: 222,
      screen_bottom: 114,
      screen_left: 227,
      button_top: 828,
      button_right: 50,
      button_bottom: 827,
      bottom_left: 2336,
      screen_width: 2048,
      screen_height: 1536,
    },
  },
  'iPadPro': {
    'portrait': {
      color: ['black', 'white', 'gold',],
      image_width: 2294,
      image_height: 3180,
      screen_top: 224,
      screen_right: 124,
      screen_bottom: 224,
      screen_left: 123,
      button_top: 3019,
      button_right: 1091,
      button_bottom: 49,
      bottom_left: 1092,
      screen_width: 2048,
      screen_height: 2732,
    },
    'landscape': {
      color: ['black', 'white', 'gold',],
      image_width: 3180,
      image_height: 2294,
      screen_top: 124,
      screen_right: 224,
      screen_bottom: 123,
      screen_left: 224,
      button_top: 1091,
      button_right: 49,
      button_bottom: 1092,
      bottom_left: 3019,
      screen_width: 2732,
      screen_height:2048,
    },
  },
  'iPhone6': {
    'portrait': {
      color: ['black', 'white', 'gold',],
      image_width: 853,
      image_height: 1771,
      screen_top: 217,
      screen_right: 50,
      screen_bottom: 220,
      screen_left: 52,
      button_top: 1582,
      button_right: 354,
      button_bottom: 47,
      bottom_left: 357,
      screen_width: 750,
      screen_height: 1334,
    },
    'landscape': {
      color: ['black', 'white', 'gold',],
      image_width: 1771,
      image_height: 853,
      screen_top: 50,
      screen_right: 220,
      screen_bottom: 53,
      screen_left: 218,
      button_top: 354,
      button_right: 47,
      button_bottom: 357,
      bottom_left: 1582,
      screen_width: 1334,
      screen_height: 750,
    },
  },
  'iPhone6Plus': {
    'portrait': {
      color: ['black', 'white', 'gold',],
      image_width: 1240,
      image_height: 2498,
      screen_top: 287,
      screen_right: 79,
      screen_bottom: 291,
      screen_left: 81,
      button_top: 2259,
      button_right: 537,
      button_bottom: 73,
      bottom_left: 537,
      screen_width: 1080,
      screen_height: 1920,
    },
    'landscape': {
      color: ['black', 'white', 'gold',],
      image_width: 2498,
      image_height: 1240,
      screen_top: 79,
      screen_right: 291,
      screen_bottom: 81,
      screen_left: 287,
      button_top: 537,
      button_right: 73,
      button_bottom: 537,
      bottom_left: 2259,
      screen_width: 1920,
      screen_height: 1080,
    },
  },
  'iPhoneSE': {
    'portrait': {
      color: ['black', 'white', 'gold', 'pink',],
      image_width: 763,
      image_height: 1601,
      screen_top: 237,
      screen_right: 58,
      screen_bottom: 228,
      screen_left: 65,
      button_top: 1417,
      button_right: 310,
      button_bottom: 49,
      bottom_left: 318,
    },
    'landscape': {
      color: ['black', 'white', 'gold', 'pink',],
      image_width: 1601,
      image_height: 763,
      screen_top: 58,
      screen_right: 228,
      screen_bottom: 65,
      screen_left: 237,
      button_top: 310,
      button_right: 49,
      button_bottom: 318,
      bottom_left: 1417,
    },
  },
  'iPhone5': {
    'portrait': {
      color: ['black', 'white',],
      image_width: 761,
      image_height: 1594,
      screen_top: 236,
      screen_right: 57,
      screen_bottom: 222,
      screen_left: 63,
      button_top: 1411,
      button_right: 308,
      button_bottom: 46,
      bottom_left: 316,
    },
    'landscape': {
      color: ['black', 'white',],
      image_width: 1594,
      image_height: 761,
      screen_top: 57,
      screen_right: 222,
      screen_bottom: 63,
      screen_left: 236,
      button_top: 308,
      button_right: 46,
      button_bottom: 316,
      bottom_left: 1411,
    },
  },
  'iPhone6Hand': {
    'portrait': {
      color: ['black', 'white',],
      image_width: 1553,
      image_height: 1384,
      screen_top: 150,
      screen_right: 860,
      screen_bottom: 303,
      screen_left: 170,
      button_top: 1103,
      button_right: 1075,
      button_bottom: 187,
      bottom_left: 385,
    },
  },
  'iPhone7Hand': {
    'portrait': {
      color: ['black',],
      image_width: 846,
      image_height: 1340,
      screen_top: 105,
      screen_right: 140,
      screen_bottom: 602,
      screen_left: 349,
      button_top: 753,
      button_right: 286,
      button_bottom: 521,
      bottom_left: 494,
    },
  },
  'iPhone7Hand_2': {
    'portrait': {
      color: ['black',],
      image_width: 846,
      image_height: 1340,
      screen_top: 105,
      screen_right: 140,
      screen_bottom: 602,
      screen_left: 349,
      button_top: 753,
      button_right: 286,
      button_bottom: 521,
      bottom_left: 494,
    },
  },
  'iPhone7': {
    'portrait': {
      color: ['black', 'white', 'gold', 'pink',],
      image_width: 870,
      image_height: 1767,
      screen_top: 212,
      screen_right: 56,
      screen_bottom: 211,
      screen_left: 54,
      button_top: 1582,
      button_right: 365,
      button_bottom: 48,
      bottom_left: 368,
    },
    'portrait_red': {
      orientation: 'portrait',
      color: ['red',],
      image_width: 314,
      image_height: 634,
      screen_top: 76,
      screen_right: 27,
      screen_bottom: 79,
      screen_left: 21,
      button_top: 569,
      button_right: 132,
      button_bottom: 16,
      bottom_left: 133,
    },
    'landscape': {
      color: ['black', 'white', 'gold', 'pink',],
      image_width: 1767,
      image_height: 870,
      screen_top: 56,
      screen_right: 211,
      screen_bottom: 54,
      screen_left: 212,
      button_top: 365,
      button_right: 48,
      button_bottom: 368,
      bottom_left: 1582,
    },
    'landscape_red': {
      orientation: 'landscape',
      color: ['red',],
      image_width: 634,
      image_height: 314,
      screen_top: 27,
      screen_right: 79,
      screen_bottom: 21,
      screen_left: 76,
      button_top: 132,
      button_right: 16,
      button_bottom: 133,
      bottom_left: 569,
    },
  },
  'Lumia930': {
    'portrait': {
      color: ['black', 'white',],
      image_width: 1483,
      image_height: 2852,
      screen_top: 203,
      screen_right: 98,
      screen_bottom: 335,
      screen_left: 82,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
    'landscape': {
      color: ['black', 'white',],
      image_width: 2852,
      image_height: 1483,
      screen_top: 98,
      screen_right: 98,
      screen_bottom: 82,
      screen_left: 203,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'Macbook': {
    'portrait': {
      color: ['black', 'white', 'gold',],
      image_width: 1916,
      image_height: 1102,
      screen_top: 80,
      screen_right: 237,
      screen_bottom: 120,
      screen_left: 237,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'Macbook2015': {
    'portrait': {
      color: ['black', 'white', 'gold',],
      image_width: 1916,
      image_height: 1102,
      screen_top: 81,
      screen_right: 238,
      screen_bottom: 120,
      screen_left: 238,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'MacbookPro': {
    'portrait': {
      color: ['black',],
      image_width: 1208,
      image_height: 700,
      screen_top: 47,
      screen_right: 142,
      screen_bottom: 76,
      screen_left: 143,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'SamsungTV': {
    'portrait': {
      color: ['black',],
      image_width: 1056,
      image_height: 683,
      screen_top: 15,
      screen_right: 15,
      screen_bottom: 86,
      screen_left: 14,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'Surface': {
    'portrait': {
      color: ['black',],
      image_width: 1579,
      image_height: 985,
      screen_top: 109,
      screen_right: 108,
      screen_bottom: 110,
      screen_left: 107,
      button_top: 908,
      button_right: 770,
      button_bottom: 41,
      bottom_left: 772,
    },
  },
  'SurfacePro3': {
    'landscape': {
      color: ['black',],
      image_width: 3621,
      image_height: 2468,
      screen_top: 175,
      screen_right: 211,
      screen_bottom: 160,
      screen_left: 211,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'SurfaceStudio': {
    'portrait': {
      color: ['black',],
      image_width: 3972,
      image_height: 3435,
      screen_top: 129,
      screen_right: 129,
      screen_bottom: 819,
      screen_left: 128,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'Chromebook': {
    'portrait': {
      color: ['black',],
      image_width: 3566,
      image_height: 2103,
      screen_top: 166,
      screen_right: 468,
      screen_bottom: 438,
      screen_left: 454,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'HtcOneM8': {
    'portrait': {
      color: ['black',],
      image_width: 320,
      image_height: 669,
      screen_top: 72,
      screen_right: 18,
      screen_bottom: 91,
      screen_left: 17,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
    'landscape': {
      color: ['black',],
      image_width: 669,
      image_height: 320,
      screen_top: 18,
      screen_right: 91,
      screen_bottom: 17,
      screen_left: 72,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'HuaweiP8': {
    'portrait': {
      color: ['gold',],
      image_width: 1119,
      image_height: 2347,
      screen_top: 214,
      screen_right: 27,
      screen_bottom: 213,
      screen_left: 19,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
    'landscape': {
      color: ['gold',],
      image_width: 2347,
      image_height: 1119,
      screen_top: 27,
      screen_right: 213,
      screen_bottom: 19,
      screen_left: 214,
      button_top: 0,
      button_right: 0,
      button_bottom: 0,
      bottom_left: 0,
    },
  },
  'Pixel': {
    'portrait': {
      color: ['black', 'white',],
      image_width: 229,
      image_height: 464,
      screen_top: 45,
      screen_right: 12,
      screen_bottom: 54,
      screen_left: 10,
      button_top: 420,
      button_right: 100,
      button_bottom: 24,
      bottom_left: 103,
    },
  },
}

export default DEVICES

export const deviceWidth = (deviceName, deviceOrientation) =>
    DEVICES[deviceName][deviceOrientation].hasOwnProperty('screen_width') ?
        DEVICES[deviceName][deviceOrientation].screen_width :
    DEVICES[deviceName][deviceOrientation].image_width
    - DEVICES[deviceName][deviceOrientation].screen_left
    - DEVICES[deviceName][deviceOrientation].screen_right

export const deviceHeight = (deviceName, deviceOrientation) =>
    DEVICES[deviceName][deviceOrientation].hasOwnProperty('screen_height') ?
        DEVICES[deviceName][deviceOrientation].screen_height :
    DEVICES[deviceName][deviceOrientation].image_height
    - DEVICES[deviceName][deviceOrientation].screen_top
    - DEVICES[deviceName][deviceOrientation].screen_bottom
